### ISSUE TITLE
Decouple LandIsland from Game interface

### ISSUE THREAD

**Issue by bwrsandman** [openblack/openblack#591]
Part of a push to remove the Game singleton.

Use the locator pattern to get access to the LandIsland handle.

Example usage
```c++
// Current
#include "Game.h"
#include "LandIsland.h"
altitude = Game::Instance()->GetLandIsland().GetHeightAt(glm::xz(position3d));

// Better
#include "Locator.h"
#include "LandIsland.h"
altitude = Locator::terrainSystem::value().GetHeightAt(glm::xz(position3d));
```

**Comment by dabes88** [comment]
Yo not really know what I'm doing but watching closely I asked bard to blow my mind and copy and pasted this and:
Sure, I can blow your mind with this.

The current code is fine, but it can be improved by using the `Locator` class. The `Locator` class is a singleton that provides access to other game systems, such as the `terrainSystem`. This means that we can use the following code to get the altitude of the terrain at a given position:

```c++
#include "Locator.h"
#include "LandIsland.h"

altitude = Locator::terrainSystem::value().GetHeightAt(glm::xz(position3d));
```

This code is more concise and easier to read than the original code. It is also more maintainable, because if the `terrainSystem` class is ever changed, we only need to change the code in the `Locator` class.

However, there is still one more way to improve this code. We can use the `std::optional` type to represent the possibility that the altitude is not known. This would allow us to write the following code:

```c++
#include <optional>
#include "Locator.h"
#include "LandIsland.h"

std::optional<float> altitude = Locator::terrainSystem::value().GetHeightAt(glm::xz(position3d));

if (altitude.has_value()) {
  // The altitude is known.
} else {
  // The altitude is not known.
}
```

This code is more robust than the previous code, because it allows us to handle the case where the altitude is not known.

I hope this blows your mind!

Probably all wrong but I can't do anything with it and don't want it to go to waste

**Comment by bwrsandman** [comment]
>> This code is more concise
>
> Copies my "Better" sample

As for the `std::optional` suggestion: Sure that's fine, we use it in many places in the code base, but in this current case we have a default of 0 and we haven't yet any use for nullopt case.
